### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/BookingScraper#10]
We don't have any tests. Contributions are welcome

**Comment by mrvnmchm** [comment]
Any specific tests we want to tackle first?

**Comment by ZoranPandovski** [comment]
@mrvnmchm  You are free to choose.

**Comment by mrvnmchm** [comment]
Thanks, just finished setting up the environment. I'll let you know when I have some verified tests.

**Comment by ZoranPandovski** [comment]
Great, thanks @mrvnmchm

**Comment by mrvnmchm** [comment]
PR #12 created for this issue
