### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by DiiegoLopez** [ZoranPandovski/BookingScraper#29]
I'm trying to use it on Mac but I got the next errors
![Captura de pantalla 2019-05-16 a las 9 51 20](https://user-images.githubusercontent.com/34645459/57836101-4bc2e200-77c0-11e9-8b81-ca6b714021fe.png)

any solution? Thank you

**Comment by ZoranPandovski** [comment]
Hi @DiiegoLopez thanks for reporting this. I will check it and get back to you.

**Comment by ZoranPandovski** [comment]
Thanks @alexlicht  for the fix. @DiiegoLopez can you test if it works for you now?
