### ISSUE TITLE
Add option for choosing file format

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/BookingScraper#3]
Currently, all of the accommodations are saved inside as JSON inside a file, we need more options e.g(CSV, excel)

**Comment by Sudip7** [comment]
Hi, m just started with python. Suggested by Linda to check with u. Can u please help in contributing to ur code?

**Comment by ZoranPandovski** [comment]
Hi @Sudip7 , please pm me on codebuddies slack, my user is Zokio.

**Comment by ZoranPandovski** [comment]
Thanks @trk9001
